name: automerge
on:
  issue_comment:
    types: [ created ]
  pull_request:
    types:
      - labeled
      - synchronize
      - edited
      - ready_for_review
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: contains(github.event.comment.body, 'merge') 
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
